"""
PatchTool — 生成标准 unified diff patch

对应原版 Claude Code 中 patch 生成能力。
不修改文件，只生成 patch 并提供可读预览。
内置敏感路径保护。
"""

from __future__ import annotations

import difflib
import time
from pathlib import Path
from typing import Optional

from pydantic import BaseModel

from .base import BaseTool


# ---------------------------------------------------------------------------
# 输入 Schema
# ---------------------------------------------------------------------------

class PatchInput(BaseModel):
    """PatchTool 的输入参数"""
    path: str                            # 目标文件路径（绝对路径或相对于 project_root）
    old_content: str                     # 文件原始内容（或要替换的片段）
    new_content: str                     # 修改后的内容
    description: Optional[str] = None    # 修改说明（写入 patch header）


# ---------------------------------------------------------------------------
# 安全策略：禁止操作的敏感路径前缀
# ---------------------------------------------------------------------------

_BLOCKED_PREFIXES: tuple[str, ...] = (
    "/etc",
    "/root",
    "/boot",
    "/sys",
    "/proc",
    "/dev",
    "/sbin",
    "/usr/sbin",
    "/lib",
    "/usr/lib",
    # Windows 系统目录
    "C:/Windows",
    "C:/Program Files",
    "C:/Program Files (x86)",
    "C:/ProgramData",
)


def _is_sensitive_path(path: Path) -> bool:
    """
    检查路径是否落在系统敏感目录下。跨平台兼容。

    匹配逻辑：
    1. resolved 路径直接以某个前缀开头（Linux 绝对路径场景）
    2. resolved 路径去除盘符后以某个前缀开头（Windows 场景）
    """
    resolved = str(path.resolve()).replace("\\", "/")
    if len(resolved) >= 2 and resolved[1] == ":":
        resolved_no_drive = resolved[2:]
    else:
        resolved_no_drive = resolved

    for prefix in _BLOCKED_PREFIXES:
        if resolved.startswith(prefix) or resolved_no_drive == prefix or resolved_no_drive.startswith(prefix + "/"):
            return True
    return False


# ---------------------------------------------------------------------------
# 工具实现
# ---------------------------------------------------------------------------

class PatchTool(BaseTool):
    """
    生成标准 unified diff patch（不修改文件）。

    根据文件的原始内容和修改后内容，生成符合标准的 unified diff patch。
    同时提供可读性强的变更预览（标注增/删/改行数）。
    """

    name = "generate_patch"
    aliases = ["Patch", "patch", "diff"]
    search_hint = "generate unified diff patch"

    def __init__(self, project_root: str = "/app/project"):
        self.project_root = project_root

    @property
    def input_schema(self) -> type[BaseModel]:
        return PatchInput

    # ------------------------------------------------------------------
    # 核心执行
    # ------------------------------------------------------------------

    async def call(
        self,
        args: dict,
        context: Optional[object] = None,
        on_progress: Optional[object] = None,
    ) -> dict:
        """
        生成 unified diff patch。

        流程:
        1. 解析并校验输入
        2. 将相对路径解析为绝对路径
        3. 安全检查（敏感路径 + 路径穿越）
        4. 检查 old_content 与 new_content 是否相同
        5. 生成标准 unified diff patch
        6. 生成可读性强的变更预览
        """
        # ---- 1. 解析输入 ----
        try:
            inp = PatchInput(**args)
        except Exception as e:
            return {"success": False, "error": f"参数校验失败: {e}"}

        # ---- 2. 解析路径 ----
        file_path = Path(inp.path)
        was_relative = not file_path.is_absolute()
        if was_relative:
            file_path = Path(self.project_root) / file_path

        # ---- 3. 安全检查 ----

        # 禁止对系统敏感路径生成 patch
        if _is_sensitive_path(file_path):
            return {"success": False, "error": f"安全限制: 禁止对系统目录生成 patch ({file_path})"}

        # 禁止路径穿越（相对路径逃逸出 project_root）
        if was_relative:
            try:
                resolved = file_path.resolve()
                root_resolved = Path(self.project_root).resolve()
                if not str(resolved).startswith(str(root_resolved)):
                    return {"success": False, "error": "安全限制: 路径逃逸出项目根目录"}
            except Exception:
                pass

        # ---- 4. 内容校验 ----
        if inp.old_content == inp.new_content:
            return {
                "success": False,
                "error": "old_content 与 new_content 完全相同，无需生成 patch",
            }

        # ---- 5. 生成 unified diff ----
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
        file_label = inp.path if was_relative else file_path.name
        desc = inp.description or "patch generated by cc-agent"

        diff_text = _build_unified_diff(
            old_text=inp.old_content,
            new_text=inp.new_content,
            old_label=f"a/{file_label}",
            new_label=f"b/{file_label}",
            timestamp=timestamp,
        )

        if not diff_text.strip():
            return {
                "success": False,
                "error": "diff 结果为空，可能内容差异仅在末尾空白字符",
            }

        # ---- 6. 生成可读预览 ----
        preview = _build_readable_preview(
            old_text=inp.old_content,
            new_text=inp.new_content,
            file_path=str(file_path),
            description=desc,
        )

        return {
            "success": True,
            "diff": diff_text,
            "preview": preview,
            "file_path": str(file_path),
            "message": f"Patch 已生成: {file_label} ({desc})",
        }

    # ------------------------------------------------------------------
    # 元信息方法
    # ------------------------------------------------------------------

    async def description(self, input_data: Optional[dict] = None, options: Optional[dict] = None) -> str:
        """返回针对当前输入的一行工具描述。"""
        path = (input_data or {}).get("path", "")
        return f"生成 Patch: {path}" if path else "生成 unified diff patch"

    async def prompt(self, options: Optional[dict] = None) -> str:
        """返回工具的完整 prompt 模板。"""
        return (
            "生成标准 unified diff patch（不修改文件）。"
            "要求提供 path（目标文件）、old_content（原始内容）和 new_content（修改后内容）。"
            "可选提供 description 说明修改目的。"
            "返回包含标准 patch 文本和可读变更预览的结果。"
            "内置安全检查：禁止对系统敏感路径生成 patch。"
        )

    # ------------------------------------------------------------------
    # 只读 & 并发安全标记
    # ------------------------------------------------------------------

    def is_read_only(self, input_data: dict) -> bool:
        """patch 生成不修改文件系统，是纯只读操作。"""
        return True

    def is_concurrency_safe(self, input_data: dict) -> bool:
        """多个 patch 生成操作之间互不影响，可以安全并发执行。"""
        return True


# ---------------------------------------------------------------------------
# 辅助函数
# ---------------------------------------------------------------------------

def _build_unified_diff(
    old_text: str,
    new_text: str,
    old_label: str = "a/file",
    new_label: str = "b/file",
    timestamp: str = "",
) -> str:
    """
    生成标准 unified diff 格式 patch。

    输出格式符合 patch 命令规范：
        --- a/file    2024-01-01 00:00:00
        +++ b/file    2024-01-01 00:00:00
        @@ -start,count +start,count @@
         context line
        -removed line
        +added line

    Args:
        old_text: 原始内容
        new_text: 修改后内容
        old_label: patch 中旧文件标签
        new_label: patch 中新文件标签
        timestamp: 时间戳字符串

    Returns:
        str: 标准 unified diff 文本
    """
    old_lines = old_text.splitlines(keepends=True)
    new_lines = new_text.splitlines(keepends=True)

    # 确保最后一行以换行结尾（difflib 要求）
    if old_lines and not old_lines[-1].endswith("\n"):
        old_lines[-1] += "\n"
    if new_lines and not new_lines[-1].endswith("\n"):
        new_lines[-1] += "\n"

    diff = difflib.unified_diff(
        old_lines,
        new_lines,
        fromfile=old_label,
        tofile=new_label,
        lineterm="",
        n=3,  # 上下文行数
    )

    lines = list(diff)

    # 注入时间戳到 header 行
    if timestamp and len(lines) >= 2:
        if lines[0].startswith("---"):
            lines[0] = f"--- {old_label}\t{timestamp}"
        if lines[1].startswith("+++"):
            lines[1] = f"+++ {new_label}\t{timestamp}"

    return "\n".join(lines)


def _build_readable_preview(
    old_text: str,
    new_text: str,
    file_path: str,
    description: str = "",
) -> str:
    """
    生成可读性强的变更预览。

    包含：
    - 修改说明
    - 文件路径
    - 增/删/改 行数统计
    - 逐行 diff 预览（带 -/+ 标记）
    """
    old_lines = old_text.splitlines()
    new_lines = new_text.splitlines()

    # 统计变更
    added = 0
    removed = 0

    sm = difflib.SequenceMatcher(None, old_lines, new_lines)
    for op, i1, i2, j1, j2 in sm.get_opcodes():
        if op == "insert":
            added += (j2 - j1)
        elif op == "delete":
            removed += (i2 - i1)
        elif op == "replace":
            added += (j2 - j1)
            removed += (i2 - i1)

    # 构建 diff 预览
    diff_lines: list[str] = []
    for line in difflib.unified_diff(
        old_lines,
        new_lines,
        fromfile="",
        tofile="",
        lineterm="",
        n=2,
    ):
        if line.startswith("---") or line.startswith("+++"):
            continue  # 跳过 header
        diff_lines.append(line)

    # 截断过长预览
    max_preview_lines = 30
    if len(diff_lines) > max_preview_lines:
        truncated = True
        shown = diff_lines[:max_preview_lines]
    else:
        truncated = False
        shown = diff_lines

    # 组装预览
    parts: list[str] = []
    if description:
        parts.append(f"说明: {description}")
    parts.append(f"文件: {file_path}")
    parts.append(f"变更: +{added} 行 / -{removed} 行")
    parts.append("")
    parts.extend(shown)
    if truncated:
        parts.append(f"... (共 {len(diff_lines)} 行 diff，已截断)")

    return "\n".join(parts)
